version: '3.4'

services:
  web:
    image: todo.app
    build:
      context: .
      dockerfile: ToDoTask/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy  

  postgres:
    image: postgres:latest
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "ToDoApp"]
      interval: 5s
      timeout: 5s
      retries: 5

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: ToDoApp
    ports:
      - "5432:5432"
